[tox]
envlist = lint,typing,py36,py37,py38,py39,py310,pypy3
skip_missing_interpreters = True
isolated_build = True
minversion = 3.3.0

[testenv]
deps =
    build~=0.7  # Must be a version that builds wheels from sdists
    setuptools>=64
    pip
    pydantic~=1.8
    pytest~=7.0
    pytest-cov~=3.0
    pytest-mock~=3.0
    wheel
commands =
    pytest {posargs:-v} test

[testenv:lint]
skip_install = True
deps =
    flake8~=4.0
    flake8-bugbear
    flake8-builtins~=1.4
    flake8-unused-arguments
commands =
    flake8 src test

[testenv:typing]
deps =
    mypy~=0.900
    types-dataclasses; python_version < "3.7"
    types-setuptools
    {[testenv]deps}
commands =
    mypy src test

[pytest]
addopts =
    --cov=versioningit
    # Explicitly setting the path to the coverage config file is necessary due
    # to some tests spawning subprocesses with changed working directories.
    --cov-config=tox.ini
    --no-cov-on-fail
filterwarnings = error
markers =
    describe_exclude: Tests that use `git describe --exclude` (Added in Git 2.13.0)
norecursedirs = test/data

[coverage:run]
branch = True
parallel = True

[coverage:paths]
source =
    src
    .tox/*/site-packages

[coverage:report]
precision = 2
show_missing = True
exclude_lines =
    pragma: no cover
    if TYPE_CHECKING:
    \.\.\.

[flake8]
doctests = True
exclude = .*/,build/,dist/,test/data,venv/
hang-closing = False
max-doc-length = 80
max-line-length = 80
unused-arguments-ignore-stub-functions = True
select = C,B,B902,B950,E,E242,F,I,U100,W
ignore = B005,E203,E262,E266,E501,I201,W503

[isort]
atomic = True
force_sort_within_sections = True
honor_noqa = True
lines_between_sections = 0
profile = black
reverse_relative = True
sort_relative_in_force_sorted_sections = True
src_paths = src

[testenv:docs]
basepython = python3
deps = -rdocs/requirements.txt
changedir = docs
commands = sphinx-build -E -W -b html . _build/html
