name: Test Installing from a Git URL

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: '0 7 * * *'

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  test-install-vcs:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        python-version:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
          - 'pypy-3.7'
          - 'pypy-3.8'
          - 'pypy-3.9'
          - 'pypy-3.10'
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install versioningit
        run: python -m pip install .

      - name: Install versioningit-test
        run: |
          python -m pip install --no-build-isolation --verbose \
            git+https://github.com/jwodder/versioningit-test
        env:
          VERSIONINGIT_LOG_LEVEL: DEBUG

      - name: Check versioningit-test version
        run: |
          version="$(pip show versioningit-test | grep ^Version: | awk '{print $2}')"
          printf "versioningit-test version: %s\n" "$version"
          if [ "$version" = "0.1.0.post2+g0a4a58d" ]
          then echo "SUCCESS!"
          else echo "FAILURE!"
               exit 1
          fi

# vim:set et sts=2:
