name: Test Against Minimum VCS Versions

on:
  pull_request:
  push:
  schedule:
    - cron: '0 6 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name}}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t minimum-vcs .github/workflows/tools/minimum-vcs

      - name: Run tests
        run: |
          docker run \
            --rm \
            -v $PWD:/docked \
            -w /docked \
            minimum-vcs \
            tox -e py -- -vv -m "not describe_exclude"

# vim:set et sts=2:
